kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: tap-install
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 31443 
    hostPort: 443
  - containerPort: 31080 
    hostPort: 80
  - containerPort: 30053 
    hostPort: 53
    protocol: udp
  - containerPort: 30053 
    hostPort: 53
    protocol: tcp
